trigger:
- main   # Runs when changes are pushed to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: mvn test
  displayName: 'Run Maven Tests'

- script: mvn package
  displayName: 'Generate build Package/Artifact'
  env:
    MAVEN_OPTIS: -DskipTests=true

- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: 'c:\agent_work' #'$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'c:\agent_work' #'$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

